#include "lexerpp.hpp"
#include <cmath>
#include <cstdio>
#include <iostream>
#include <stack>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

enum AST_node_type {
  program_node,
  print,
  declare_and_assign,
  expression,
  identifier_name,
  type_identifier,
};

enum variable_types {
  int_type,
  float_type,
  string_type,
};

enum bin_operators {
  plus,
  minus,
  times,
  divide,
};

class base_ast_node {
public:
  base_ast_node *parent = nullptr;
  std::vector<base_ast_node *> children;
  AST_node_type node_type; // temporary until hierarchy is added

  void set_parent(base_ast_node *parent_to_set) { parent = parent_to_set; }

  void add_child(base_ast_node *child_to_add) {
    children.emplace_back(child_to_add);
  }

  virtual ~base_ast_node() = default;
};

class identifier_node : public base_ast_node {
public:
  std::string value;

  void set_value(std::string identifier_name) { value = identifier_name; }

  virtual ~identifier_node() = default;
};

class type_identifier_node : public base_ast_node {
public:
  variable_types type;

  void set_value(variable_types t) { type = t; }

  virtual ~type_identifier_node() = default;
};

class expression_node : public base_ast_node {
public:
  std::variant<int, float, std::string> value;
  virtual ~expression_node() = default;
};

class binary_operator : public base_ast_node {
public:
  bin_operators operator_type;
  virtual ~binary_operator() = default;
};

class Lang {
public:
  std::vector<Token> tokens;
  int line_nr = 0;
  bool buffer_occupied = false;
  std::stack<Token> token_wait_area;
  std::stack<Token> inline_tokens;
  std::vector<std::string> errors;

  Lang(std::vector<Token> toks) {
    toks.erase(toks.end() - 2);
    for (int i = toks.size() - 1; i >= 0; i--) {
      inline_tokens.push(toks[i]);
    }
  }

  void stack_collapse() { // token wait area is the stack above inlien tokens
    while (!token_wait_area.empty()) {
      Token top_token = token_wait_area.top();
      token_wait_area.pop();
      inline_tokens.push(top_token);
    }
  }

  void add_error(std::string message) {
    errors.emplace_back("ERROR line " + std::to_string(line_nr) + ": " +
                        message);
  }

  Token next_token() {
    if (inline_tokens.empty()) {
      throw std::runtime_error("inline_tokens are empty");
    }

    Token top_token = inline_tokens.top();
    inline_tokens.pop();
    return top_token;
  };

  bool parse_program(base_ast_node *program_node) {

    // program = <statement> + [statement + ...]

    program_node->node_type = AST_node_type::program_node;

    // try to parse the first statement
    if (!parse_statement(program_node)) {
      throw std::runtime_error("failed to parse first statement");
      return false;
    }

    while (inline_tokens.top().value != "END") {
      if (!parse_statement(program_node)) {
        return false;
      }
    }

    return true;
  }

  bool parse_statement(base_ast_node *parent) { return true; }

  bool parse_print_statement(base_ast_node *parent) { return true; };
};

// return number of tokens generated by lexer()
int count_tokens(Token *tokens_list) {
  int count = 0;

  while (tokens_list[count].type != END) {
    count++;
  }

  return count;
}

std::string give_node_type_string(base_ast_node *node) {

  switch (node->node_type) {
  case AST_node_type::program_node:
    return "program_node";
  case AST_node_type::print:
    return "print_node";
  case AST_node_type::identifier_name:
    return "Identifier_node";
  case AST_node_type::declare_and_assign:
    return "variable_declaration_&_assignment_node";
  case AST_node_type::expression:
    return "expression_node";
  case AST_node_type::type_identifier:
    return "type_identifier_node";
  }

  return "node was not assigned type";
}

void print_tree_from_node(base_ast_node *node, int depth) {
  std::cout << std::string(depth, '-') << give_node_type_string(node) << ": ";

  if (const identifier_node *i_node = dynamic_cast<identifier_node *>(node)) {
    std::cout << i_node->value;
  }

  if (const type_identifier_node *i_node =
          dynamic_cast<type_identifier_node *>(node)) {
    if (i_node->type == variable_types::int_type) {
      std::cout << "int";
    } else if (i_node->type == variable_types::float_type) {
      std::cout << "float";
    } else if (i_node->type == variable_types::string_type) {
      std::cout << "string";
    }
  }
  // lol
  if (const expression_node *e_node = dynamic_cast<expression_node *>(node)) {
    std::visit([](auto &&arg) { std::cout << arg << std::endl; },
               e_node->value);
  }

  std::cout << "\n";

  if (node->children.size() == 0) {
    return;
  } else {
    for (int i = 0; i < node->children.size(); i++) {
      print_tree_from_node(node->children[i], depth + 1);
    }
  }
}

void printGreen(const std::string text) {
  std::cout << "\033[32m" << text << "\033[0m" << std::endl;
}

void printRed(const std::string text) {
  std::cout << "\033[31m" << text << "\033[0m" << std::endl;
}

int main(int argc, char **argv) {

  std::string file_name = argv[1];

  std::ifstream fileObject{file_name};

  std::vector<Token> tokens = lexer(fileObject);

  base_ast_node root;

  Lang e(tokens);
  bool result = e.parse_program(&root);

  if (result) {
    printGreen("Compilation was a success!");
  } else {
    printRed("Compilation not succcesful :(");
  }

  print_tree_from_node(&root, 0);

  return 0;
}
